HELLO = 'VAGOAMIN-HELLO'

BYE = 'VAGOAMIN-BYE'

APP_VERSION = '0001'

#HEADER = '01xSOM01x'
HEADER = 'VAGOAMIN-' + APP_VERSION

CHAR_SET = 'utf-8'

DEFAULT_PORT = 8421

DEFAULT_SERVERNAME = 'localhost'

DATAHEADER = 'JSON='